lib/data/ecogest_api_data_source.dart, lib/state_management/posts/posts_cubit.dart, lib/widgets/comment/comments_list.dart, lib/widgets/post/one_post_widget.dart, lib/widgets/post/post_content_author.dart
lié à ma PR du back: https://github.com/Eco-Gest/Backend-Laravel/pull/15
=> keep post when author deleted

lib/services/user_service.dart, lib/widgets/account/update_account_widget.dart
https://github.com/Eco-Gest/Frontend-Flutter/issues/39
https://github.com/Eco-Gest/Frontend-Flutter/issues/38
=> fix error update user profil

lib/state_management/user/user_cubit.dart, lib/views/legal/change_password_view.dart, lib/views/users/user_view.dart, lib/widgets/post/post_content_infos.dart
https://github.com/Eco-Gest/Frontend-Flutter/issues/40
=> fix error user view

lib/widgets/account/account_infos.dart, lib/widgets/account/subscriptions_list_widget.dart, lib/widgets/account/user_profile_menu.dart
https://github.com/Eco-Gest/Frontend-Flutter/issues/41
=> fix bugs follow actions user view

lib/services/participation_service.dart, lib/services/post_service.dart, lib/state_management/posts/participation_cubit.dart, lib/widgets/challenge_widget.dart, lib/widgets/post/one_post_widget.dart, lib/widgets/post/participation_widet.dart, lib/widgets/post/post_content_buttons.dart, lib/widgets/post/posts_list.dart
=> mark challenge as completed

lib/views/users/user_view.dart
https://github.com/Eco-Gest/Frontend-Flutter/issues/45
=> add PostsUserviewWidget to user view

lib/views/auth/login_view.dart, lib/views/auth/register_view.dart, lib/views/auth/reset_password_view.dart, lib/views/legal/change_password_view.dart, lib/views/settings_view.dart
ajout de marge en haut pour page connexion, mdp oublié et s'inscrire
le bouton se deco n'était pas du bon type
Faute de frappe c'est écrit "nouvaeu mot de passe" et non "nouveau"
=> Us 35 f1 auth pages UI

lib/state_management/search/search_cubit.dart, lib/widgets/search/search_bar_widget.dart, lib/widgets/search/search_results_widget.dart
- retirer les espace de début et fin avant de lancer la requête de recherche
- mettre bouton recherche iso au reste de l'app
=> trim query before searching

lib/data/ecogest_api_data_source.dart, lib/main.dart, lib/views/posts/post_create_view.dart, lib/widgets/account/update_account_widget.dart, lib/widgets/post/post_form_widget.dart, pubspec.lock, pubspec.yaml
- Bien afficher la date de naissance du user si il en a une dans la partie éditer profil
- Les dates sont en de nouveau en français
=> Bug champs de dates

android/app/src/main/AndroidManifest.xml, lib/data/ecogest_api_data_source.dart, lib/main.dart, lib/views/posts/post_create_view.dart, lib/widgets/account/update_account_widget.dart, lib/widgets/post/post_form_widget.dart, pubspec.lock, pubspec.yaml, windows/flutter/generated_plugin_registrant.cc, windows/flutter/generated_plugins.cmake
Dans cette PR :
- ajout de l'api key pour la requête upload image
-  ajout d'une demande de permission pour accéder aux storage interne du téléphone
- modifications de l'UX pour l'ajout d'image (profil et publication) : 
- bouton circulaire ou carré 
- à l'upload l'image s'affiche avant de soumettre le formulaire
- à l'édition du profil ou post on charge l'image actuelle
note : cette PR a été développé sur android, la version web a volontairement été mise de côté même si elle semble fonctionner
=> Bug upload images

lib/main.dart, lib/state_management/authentication/authentication_cubit.dart, lib/state_management/authentication/authentication_state.dart, lib/views/auth/login_view.dart, lib/views/loading_view.dart, lib/widgets/loading_widget.dart
Ajout d'une page de loading lors du login mais également lorsqu'on réouvre l'app (ou hot restart) afin d'éviter de voir la home alors qu'on est co
=> 66 bug ouverture de lapp

lib/core/router.dart, lib/main.dart, lib/views/legal/legal_notices_view.dart, lib/views/legal/privacy_policy_view.dart, lib/views/settings_view.dart
- changer [contact@ecogest.dev](mailto:contact@ecogest.dev) par [contact@ecogest.org](mailto:contact@ecogest.org)
- mettre à jour les données
- changer le nom des vues pour coller au reste
- passe design
=> update legal views

lib/views/posts/post_create_view.dart, lib/widgets/post/post_form_widget.dart
Cette PR vise à améliorer l'expérience utilisateur lors de la création d'une publication. L'ancien comportement observé réinitialisaient les champs dates lorsque l'utilisateur intéragissait avec d'autres champs. Le but est de garantir que les dates sélectionnées par l'utilisateur sont valides et logiques avant la soumission, tout en fournissant des messages d'erreur clairs et explicites lorsque les dates ne sont pas correctement renseignées.
1. **Sauvegarde de la date dans le state du widget**
- Ajout de la méthode  `setState ` qui met à jour l'état du widget en modifiant la valeur de `endDate ` ou `startDate ` avec la nouvelle date sélectionnée (value)
2. **Initialisation des dates par défaut** :
- `startDate` est initialisée à la date actuelle.
- `endDate` est initialisée à un jour …
=> BUG : les champs dates du formulaire depublication se réinitialise lors d'intéraction avec d'autres champs

lib/widgets/post/post_footer/post_footer.dart, lib/widgets/post/post_footer/post_footer_participation.dart
https://github.com/orgs/Eco-Gest/projects/4/views/5?pane=issue&itemId=71631903
=> modals to participate & end a challenge

lib/widgets/account/approve_or_decline_subscription_widget.dart, lib/widgets/account/subscription_widget.dart, windows/flutter/CMakeLists.txt
les boutons suivre/annuler et gérer la demande on des tailles ne débordent plus
=> fix subscription widget buttons layout

lib/data/ecogest_api_data_source.dart, lib/main.dart, lib/views/search_view.dart, lib/widgets/search/search_bar_widget.dart, lib/widgets/search/search_results_widget.dart
https://github.com/Eco-Gest/Frontend-Flutter/issues/82
=> fix bugs on search page

lib/services/post_service.dart, lib/state_management/posts/posts_cubit.dart, lib/views/home_view.dart, lib/views/posts/post_detail_view.dart, lib/views/posts/post_edit_view.dart, lib/widgets/post/post_footer/post_footer_participation.dart, lib/widgets/post/post_header/post_header_infos_actions.dart, lib/widgets/post/posts_list.dart, lib/widgets/post/single_post.dart
J'ai supprimé le cache sur flutter. Ca résout pas mal de bugs d'affichage + mise à jour du post footer
=> remove flutter cache + update post footer

lib/data/ecogest_api_data_source.dart, lib/widgets/comment/comment_content_menu.dart, lib/widgets/comment/comment_element.dart, lib/widgets/comment/comments_list.dart, lib/widgets/post/post_footer/post_footer.dart, lib/widgets/post/post_footer/post_footer_infos.dart, lib/widgets/post/post_header/post_header_infos_actions.dart
This PR includes several improvements and changes to the comment section. The following modifications were made:
1. **Comment Layout Redesign:**
- Reorganized the layout of the comments into a three-column structure:
- **First Column:** Displays the user's avatar aligned at the top.
- **Second Column:** Contains the username aligned at the top, with the comment text directly beneath it.
- **Third Column:** Holds the `CommentContentMenu` aligned at the top.
- Adjusted padding to have less horizontal space than vertical space for a cleaner look.
2. **Clickable Comment Count:**
- Added functionality to make the number of comments clickable.
- This link now navigates the user to the comment section, enhancing the user experience by making it easier to jump directly to the comments.
3. …
=> UI and Bugs on comments

lib/state_management/authentication/authentication_cubit.dart, lib/state_management/posts/posts_cubit.dart, lib/state_management/user/user_cubit.dart, lib/state_management/user/user_state.dart, lib/views/legal/change_password_view.dart, lib/views/posts/post_create_view.dart, lib/views/users/account_view.dart, lib/views/users/user_view.dart, lib/widgets/account/update_account_widget.dart, lib/widgets/post/post_form_widget.dart
La homepage ne se met pas à jours lorsque l'on créeune publication ou modifie une publication. Idem le profil ne se met pas à jour après la modificaiton des infos du profil.
Ouvrir l'application.
Se rendre sur le profil d'un utilisateur
Modifier le profil
Valider
OU
Créer une publication 
OU
Modifier une publication
Pour les publis :
```dart
GoRouter.of(context).pushNamed(HomeView.name).then((_) {
setState(() {});
});
```
pour le profil : 
lier le cubit auth à l'user afin de pouvoir emettre les infos du user dans le state auth
lib/state_management/authentication/authentication_cubit.dart
lib/state_management/posts/posts_cubit.dart
lib/state_management/user/user_cubit.dart
lib/state_management/user/user_state.dart
lib/views/legal/change_password_view.dart …
=> Rechargement de l'app lors d'une publi ou modification du profil

android/app/build.gradle, android/build.gradle, android/gradle/wrapper/gradle-wrapper.properties, pubspec.lock, pubspec.yaml
=> upgrade packages
